### ISSUE TITLE
Web App broken in Ipados

### ISSUE THREAD

**Issue by EmmanuelRoyOurBoy** [gameplaycolor/gameplaycolor#106] opened 2019-10-09 19:30 UTC
A couple of notifications pop up and then a pitch black screen appears.

**Comment by nickydraz** [comment] 2019-10-19 01:11
This is likely the same issue as #103 . I have created a PR #108 that should fix the issue.

**Comment by Zosoled** [comment] 2019-12-25 02:38
Should be closed as duplicate of #103

**Comment by jbmorley** [comment] 2021-05-16 14:27
Closing as a duplicate. Thanks @Zosoled.

**Closed by jbmorley** 2021-05-16 14:27 UTC
