### ISSUE TITLE
New way to import games

### ISSUE THREAD

**Issue by G9-Dev** [gameplaycolor/gameplaycolor#213] opened 2021-10-13 20:11 UTC
Hello
Here is my (kinda weird) problem : I can't login to Google anymore. Like, really. I don't know why my Safari is like that, plus login works with Chrome app. But that's not why I opened this issue lol 🤪
Can you either add another way to import games, or some way to get the key to access GamePlay ?

EDIT : wow I can't believe I've found a workaround. I had to copy the url on the top into Chrome.

**Comment by jbmorley** [comment] 2022-02-02 06:35
@G9-Dev Sorry for the late reply. Really happy to hear you found a work around. 👌🏻

I'm going to close this as a duplicate of #46.

**Closed by jbmorley** 2022-02-02 06:35 UTC
