### ISSUE TITLE
Playing around with the Offline Issue on iOS 15. (Both Brandosha’s Fork & Game Play)

### ISSUE THREAD

**Issue by JonhMunoz** [gameplaycolor/gameplaycolor#211] opened 2021-08-28 16:10 UTC
So for the last few days I’ve been playing around trying to figure out how to get the offline mode to work again on both Brandosha’s Fork & the Original Game Play Fork. I’ve noticed that Brandosha’s Fork lasts offline for about 5 minutes if you have it closed then when you try to go on it say without any data or wifi connection it goes to offline. As to Game Play Fork in general if I try to go offline after closing and killing any data or wifi signal, safari immediately says I don’t have any connection and that leads to the offline issue. I haven’t tried playing around with the experimental features yet as iOS 15 itself is down to its final days of the Beta Testing and will soon launch Into the Public Update itself. Here’s a Screen Recording of what I mean.

**Comment by JonhMunoz** [comment] 2021-08-28 17:00
![Uploading E2F01860-7829-4348-A312-001A322FE89D.png…]()

**Comment by JonhMunoz** [comment] 2021-08-28 17:11
Unfortunately GitHub is not letting me upload any screen recordings of screenshots. If there’s anywhere I can submit them please let me know. I would like for you guys to see the issue. Thank You so Much and Happy Saturday! 😊

**Comment by jbmorley** [comment] 2021-08-28 20:13
cc @brandosha

**Comment by jbmorley** [comment] 2024-08-29 19:40
Closing this as a dupe of #210 which I'm currently using to track offline support.

**Closed by jbmorley** 2024-08-29 19:40 UTC
