### ISSUE TITLE
iPhone Controller Support?

### ISSUE THREAD

**Issue by Vulcan013** [gameplaycolor/gameplaycolor#131] opened 2020-02-16 20:50 UTC
Would it be possible to give this Controller Support with things like the Logitech Powershell from the iPhone 5 and SE Size Series? https://www.amazon.com/Logitech-PowerShell-Controller-Battery-Generation/dp/B00FHREO8K

**Comment by mayeslad** [comment] 2020-02-17 04:47
Possibly PS4 and Xbox controllers would also be great now they can connect to iPhones?

**Comment by drinkdrpepper** [comment] 2020-07-04 16:23
This is something I would very much appreciate. I have carpal tunnel and holding the phone to play hurts my fingers after a short while.

**Comment by jbmorley** [comment] 2021-05-25 21:47
Duplicate of #57.

**Closed by jbmorley** 2021-05-25 21:47 UTC
