### ISSUE TITLE
iPhone XS Max Landscape Issues

### ISSUE THREAD

**Issue by cspeloso** [gameplaycolor/gameplaycolor#140] opened 2020-05-17 17:28 UTC
Hello, I’m using an iPhone XS Max. The app orientation doesn’t work correctly in landscape mode.
![53A3E3F1-7693-47F2-AC9A-8FCEB9747F15](https://user-images.githubusercontent.com/36888899/82155344-343e8f00-9842-11ea-8f57-564bbe291171.png)

![A0D2DE16-904A-4F87-A41B-AF0B9F90863E](https://user-images.githubusercontent.com/36888899/82155348-3e608d80-9842-11ea-954d-354562a41647.png)

 I was wondering if there will be any fixes for this. It’s been like this since I got my new phone (somewhere around October 2018, still broken)

**Comment by jbmorley** [comment] 2021-05-25 21:58
Ooof. That looks pretty bad! 😢 I'll take a look at some point, but it's likely to be a while before I get around to it.

**Comment by jbmorley** [comment] 2021-05-25 22:45
Closing this as a duplicate of #89 which is tracking _all_ landscape issues.

**Closed by jbmorley** 2021-05-25 22:45 UTC
Labels: bug
