### ISSUE TITLE
Add some support for Cable Link

### ISSUE THREAD

**Issue by redpenguinyt** [gameplaycolor/gameplaycolor#214] opened 2021-10-24 09:15 UTC
Something like a bluetooth connection to other game play emulators, so if 2 people have Game Play installed, they can e.g. play mario tennis together or trade pokemon via Bluetooth

**Comment by jbmorley** [comment] 2022-01-13 16:40
Duplicate of #55.

**Closed by jbmorley** 2022-01-13 16:40 UTC
