### ISSUE TITLE
Add support for GB and GBC ROM hacks

### ISSUE THREAD

**Issue by Shawnjoseph2001** [gameplaycolor/gameplaycolor#75] opened 2016-10-07 23:34 UTC
If you currently upload a ROM hack, such as Pokemon Brown or a Gen 2 graphics version of Pokemon Red/Blue to Google Drive and launch Game Play Color, the ROM won't show up. It would be nice if you could add support for ROM hacks in the future.

**Comment by jbmorley** [comment] 2016-10-09 10:57
The only thing which determines whether a game turns up in the game list is the file extension. If you rename it to `.gb`, does the ROM work?

**Comment by Nythepegasus** [comment] 2016-10-09 13:42
@jbmorley If you rename it to .gbc it'll show up, but that doesn't mean it'll work, .gb files and .gbc files have different setups because they're made for different platforms. At the moment Gameplay Color can only support .gbc files (as far as i'm aware) so renaming it won't do anything.

**Comment by jbmorley** [comment] 2016-10-09 13:45
Internally the emulator core doesn't use the extension to determine the ROM format; it reads that from the ROM data itself. If the hacked ROMs follow the same ROM layout as their corresponding Game Boy or Game Boy Color ROMs, I don't see why they shouldn't work.

Or do they contain some additional post-load memory patches, etc?

**Comment by Nythepegasus** [comment] 2016-10-09 13:48
@jbmorley Sorry, I sounded dumb on my earlier post, and I revised it. My brain didn't function correctly for a few seconds..

**Comment by jbmorley** [comment] 2016-10-09 13:51
@Nythepegasus Thanks for the clarification. Yes, if he's trying to play GBA games they won't work. I had, perhaps incorrectly, assumed that the request was for GB and GBC hack support.

**Comment by Shawnjoseph2001** [comment] 2017-01-22 01:14
I wasn't talking about GBA games (SNES games don't run on the NES, either). I was referring to the fact that some GB/GBC Rom hacks show up as audio files in Google Drive and aren't registered by Game Play Color, such as a Rom Hack of Pokemon Red with Gen 2 graphics.

**Comment by jbmorley** [comment] 2021-05-25 23:41
Well, it only took me 5 years to triage this. Look like a duplicate of #69.

**Closed by jbmorley** 2021-05-25 23:41 UTC
