### ISSUE TITLE
Harry Potter games freeze the console

### ISSUE THREAD

**Issue by MarioRNR** [gameplaycolor/gameplaycolor#138] opened 2020-04-05 19:18 UTC
Hi everyone! I'm new in the site and I have a problem only with Harry Potter roms for GBC.
After a few minutes the game freeze and there is no turning back, I have to re-launch the console or the game. But here is the odd things, it only happends with Harry Potter roms! I've tried a bunch of different roms, still not work for me. Tested with HP Philosopher's Stone, and Chamber of Secrets

Any suggestions?
(I have an iPhone 7 32GB with iOS13.3.1)

**Comment by jbmorley** [comment] 2021-05-26 00:03
Looks like this might be a core issue...

**Comment by jbmorley** [comment] 2024-08-29 22:05
Well, I was definitely able to reproduce this.

**Comment by jbmorley** [comment] 2024-08-31 05:50
After further consideration, I don't think it makes sense to look into core issues at this point in time. There are great iOS emulation alternatives these days (see [Delta](https://apps.apple.com/app/delta-game-emulator/id1048524688)) and the need for Game Play just isn't there in the same way. Closing as won't fix.

**Closed** 2024-08-31 05:50 UTC
Labels: bug, wontfix, core
