### ISSUE TITLE
No sound even with Sound Enabled

### ISSUE THREAD

**Issue by Schinkidink95** [gameplaycolor/gameplaycolor#230] opened 2023-01-10 15:47 UTC
So I was playing Polished Crystal for a while on the Game Play Color with the sound enabled. I’ve turned it off to take a break. When I got back to it, the sound is gone. I pretty much have to wait until the option to have sound enabled becomes available again (restarting my phone for example) or play it in one sitting. I never had the problem when I first got it.

**Comment by jbmorley** [comment] 2023-01-10 16:07
Does quitting Game Play Color from the app switcher help?

**Comment by Schinkidink95** [comment] 2023-01-10 16:08
Nope. I have to wait until it resets for the sound enabling option becomes available.


Sent from Yahoo Mail for iPhone


On Tuesday, January 10, 2023, 8:07 AM, Jason Morley ***@***.***> wrote:




Does quitting Game Play Color from the app switcher help?

**Comment by jbmorley** [comment] 2023-01-10 16:40
That's unfortunate. I wonder if this is an iOS regression.

**Comment by jbmorley** [comment] 2024-08-29 21:31
I'm going to close this as 'invalid' as I've been unable to reproduce the issue on any of my devices. I've not see sound fail in a few years, and when it does, force closing Game Play by entering the task switcher and swiping Game Play up and off the screen means it will ask again if it should enable sound on first run.

**Closed** 2024-08-29 21:32 UTC
Labels: bug, invalid
