### ISSUE TITLE
Possible issue with iOS 14.6

### ISSUE THREAD

**Issue by Kadgar64** [gameplaycolor/gameplaycolor#208] opened 2021-07-04 13:04 UTC
I'm not sure if it's the ios support or something I did, but for some reason a black screen appears over the app that I can scroll down but pops right back over the settings and console screen and I have no idea how to get rid of it. Thanks for any support you have. Have a great Sunday.

**Comment by jbmorley** [comment] 2021-07-05 18:20
I've not seen this issue myself, but I don't have a device to hand to test on for a week-or-so; I'll take a look when I get back. I'd love to hear if it changes for you, or if anyone else is seeing these problems. Thanks in advance!

**Comment by jbmorley** [comment] 2021-07-05 18:29
@Kadgar64 I understand things are working fine on iOS 15 beta, so I'd be surprised if it's an issue with iOS 14.6. Would you be able to attach a screen recording of the issue? You can find instructions of how to do this on https://support.apple.com/en-us/HT207935.

**Comment by dgothing** [comment] 2021-07-06 04:20
The same happened to me. I’m on iOS 14.6 as well. I had been playing a game, then went to look at something. When I opened the game again I got this black screen. It’s still happening after force closing the app.

https://user-images.githubusercontent.com/48682548/124541551-e0dd2680-ddde-11eb-83b9-00368d70c1b2.MP4

**Comment by jbmorley** [comment] 2021-07-06 17:03
@dgothing Thanks so much for the feedback. Does it persist after a reboot?

**Comment by BubblyGumKrisk** [comment] 2021-07-06 18:48
@jbmorley The same problem happens with me, and rebooting does not fix the issue.

**Comment by jbmorley** [comment] 2021-07-06 19:12
Ooof.@BubblyGumKrisk Are you also on iOS 14.6?

As I say, unfortunately I don't have a device to test on this week so I'll try to take a look next week. Seems like maybe its a timing issue / race condition with the new OS. 🤔

**Comment by Kadgar64** [comment] 2021-07-06 22:56
That video did have the problem I ran into, sorry I didn't get a chance to reply sooner

**Comment by Kadgar64** [comment] 2021-07-06 23:24
I also have it randomly working without any real reason other than completely closing and opening it a random number of times

**Comment by jbmorley** [comment] 2021-07-06 23:32
Sounds like a pretty good idea of the symptoms at least; thank you both for your help! Interesting that it's intermittent. Let's hope I can repro it when I get back to an iPhone. 😅

**Comment by MDMcNugget** [comment] 2021-07-25 07:12
Using iOS 14.7 and am facing the same problem. Was about to comment that I couldn't open the app no matter how many times I tried, but I finally got it to work after 40 or so tries lol 😂

**Comment by jbmorley** [comment] 2021-07-27 15:08
This definitely seems to be an intermittent problem for me. I did manage to reproduce it on my iPad running 14.6 (I think) but it went away soon after and I've not seen it again.

**Comment by jbmorley** [comment] 2024-08-29 17:58
Looks like this has been fixed on Apple's side a _loooooong_ time ago. Closing.

**Closed by jbmorley** 2024-08-29 17:58 UTC
Labels: bug, needs investigation
