### ISSUE TITLE
Doesn’t work in new iOS versions

### ISSUE THREAD

**Issue by ghost** [gameplaycolor/gameplaycolor#129] opened 2020-02-05 16:14 UTC
I have my iPad at iOS 13.3.1 and it never loads now. It doesn’t load for iOS 13.3 either
![5196582C-0B22-454B-8C63-948336994A94](https://user-images.githubusercontent.com/58752579/73859799-a0076980-4808-11ea-8ff7-f0cf792283d4.png)

**Comment by brandosha** [comment] 2020-02-12 13:35
This appears to be a duplicate of #123 

It is also the same issue that I had on my fork: https://github.com/brandosha/gameplaycolor/issues/4

**Comment by jbmorley** [comment] 2021-05-26 00:10
Thanks @brandosha. It is indeed a duplicate of #123. Closing as such.

**Closed by jbmorley** 2021-05-26 00:10 UTC
Labels: bug
