### ISSUE TITLE
Is it possible to trade pokemon on the emulator?

### ISSUE THREAD

**Issue by GaleofD** [gameplaycolor/gameplaycolor#144] opened 2020-07-10 20:23 UTC
Hello Dev,
I want to trade pokemon since some only evolve by trading with other players, but this emulator isn't able to connect to other people's devices the ways other emulators can, I don't think. Will a feature that might enable something like pokemon trading be added to your emulator anytime soon?

Thank you for your work, I'm happy to play gbc games again. :)

**Comment by RobRobRobson** [comment] 2021-05-15 17:44
Hi GaleofD, Hi Dev,

is there any news on this?

The emulator is almost perfect. The trading function is the only thing that would make the emulator better.
Thank you for your efforts!

**Comment by jbmorley** [comment] 2021-05-15 20:21
Thanks for raising this issue. It's actually a duplicate of #55, so I'm going to close it as such. Please follow along there if you're interested in this feature. It's definitely something I'd love to add support for, but like many of the larger features, it's probably going to be a while before I get a chance to look into it seriously.

**Closed** 2021-05-15 20:21 UTC
Labels: duplicate, enhancement
