### ISSUE TITLE
Game crashes and lose saves - Quick way to back up saves to iPhone

### ISSUE THREAD

**Issue by mbsync** [gameplaycolor/gameplaycolor#120] opened 2019-12-13 10:45 UTC
Game play keeps crashing and when it does i lose the save data for whatever game I was playing, is there a quick way to back it up so I don’t play hours and lose it? Any help would be appreciated

**Comment by Josepsh** [comment] 2020-05-09 20:55
Game play keeps crashing and when it does i lose the save data for Pokémon crystal game I was playing, is there a quick way to back it up so I don’t play hours and lose it? Any help would be appreciated

**Comment by jbmorley** [comment] 2021-05-25 22:44
Are you loosing _all_ save data, or data since your last save? Thanks.

**Comment by jbmorley** [comment] 2024-08-29 21:24
So in the interests of trying to get a better idea of the state of things and track clear issues that can be addressed, I'm going to close this as a dupe of #46 which tracks supporting import and export of saves.

**Closed** 2024-08-29 21:25 UTC
Labels: bug, duplicate
