### ISSUE TITLE
Layout bug on landscape

### ISSUE THREAD

**Issue by Pr0sT69** [gameplaycolor/gameplaycolor#97] opened 2019-01-26 17:18 UTC
iPhone SE; iOS 12.1.3; half of the gamescreen is out of display, buttons also moved down.. sorry for the grammar

**Comment by MertDalbudak** [comment] 2019-08-12 08:15
Same

**Comment by jbmorley** [comment] 2021-05-25 22:18
Landscape definitely needs some work across all devices.

Closing this as a duplicate of #89. Please feel free to follow along there. 🎉

**Closed by jbmorley** 2021-05-25 22:18 UTC
