### ISSUE TITLE
Save only saves a bit

### ISSUE THREAD

**Issue by keith1407** [gameplaycolor/gameplaycolor#149] opened 2021-01-29 08:33 UTC
The safe only saves half of what you have saved

**Comment by jbmorley** [comment] 2021-05-25 21:36
Are you able to provide any more detail? Was this with a specific ROM? Thanks!

**Comment by jbmorley** [comment] 2021-05-28 21:00
Possible duplicate of #142?

**Comment by jbmorley** [comment] 2024-08-29 20:57
I'm not a big fan of closing things as stale, but without more information, I don't think as I can look into this. Closing as not planned.

**Closed** 2024-08-29 20:57 UTC
Labels: bug
