### ISSUE TITLE
GBA support?

### ISSUE THREAD

**Issue by dheg** [gameplaycolor/gameplaycolor#232] opened 2023-02-13 04:20 UTC
Is it possible to add support for GBA games?

**Comment by jbmorley** [comment] 2024-08-29 17:45
This is essentially a duplicate of #155; right now my thinking is that I'll not add any other system support to Game Play. There are many more options available on iOS these days and I think I'd probably approach things in a very different way if I decided to write a multi-system emulator.

**Closed** 2024-08-29 17:45 UTC
Labels: enhancement
