### ISSUE TITLE
Better buttons

### ISSUE THREAD

**Issue by BamhamYT** [gameplaycolor/gameplaycolor#77] opened 2016-10-18 02:25 UTC
Im not sure if this is for everyone but it is hard to press the right or left with accidently hitting down or up so make the button layout better so that wont happen more often, also sometimes i click the select or start button and it takes me around 5 times to make it work same with the dpad but less often.

**Comment by Shawnjoseph2001** [comment] 2016-11-03 05:46
Adding on to this, it would be nice if you could choose wether or not to have the darker highlight area in the center of the control area as it appears ip Portrait mode, it looks a bit odd when the phone is put into landscape mode.

**Comment by Someone516** [comment] 2017-05-08 02:32
+1

**Comment by rytina** [comment] 2017-05-21 16:38
+1

**Comment by jbmorley** [comment] 2021-05-25 22:16
I agree there should be things we can do to improve the button situation, especially with bigger screened phones. This is technically a duplicate of #70 so I'm going to close this and track it there. Open to all suggestions 👌🏻.

**Closed by jbmorley** 2021-05-25 22:16 UTC
