### ISSUE TITLE
iCade Support

### ISSUE THREAD

**Issue by MaquinaDelMisterio** [gameplaycolor/gameplaycolor#80] opened 2017-01-07 22:38 UTC
I was looking for something easy and simple to use, like this GBA and GBC emulator, but i own an iPad Pro 13" so using touch screen is painfull, so can someone please add iCade support for 8bitdo controllers, please.

**Comment by Shawnjoseph2001** [comment] 2017-03-23 06:25
This will probably never be added due to the limitations of Web based apps. If you want to use something with iCade or 8bitdo support, sideload an actual app-based emulator with Cydia Impactor on a computer like GBA4iOS and use that instead.

**Comment by MaquinaDelMisterio** [comment] 2017-03-23 12:44
Geez, how bad. It would have been amazing. Thanks for the info.

**Comment by jbmorley** [comment] 2021-05-25 21:46
Duplicate of #57.

**Closed by jbmorley** 2021-05-25 21:46 UTC
