### ISSUE TITLE
Game Play doesn't work on iPadOS

### ISSUE THREAD

**Issue by Hansondpaul** [gameplaycolor/gameplaycolor#123] opened 2019-12-20 17:06 UTC
I saved the app to the home screen, but the app simply opens as if I loaded the app in safari. If I scroll up I can see the menus for selecting a game, but it is loaded under the screen telling me how to install the emulator.

**Comment by imethorsen** [comment] 2019-12-20 17:43
What device are you using this on?

**Comment by Hansondpaul** [comment] 2019-12-21 00:02
I apologize for not specifying in the original post. This is on an IPad, 6th generation, with IPadOS 13.2.3.

**Comment by imethorsen** [comment] 2019-12-21 00:14
Thanks for clarifying. Safari on iPadOS reports itself differently, so it's possible this is a side effect of that. We can investigate.

**Comment by Hansondpaul** [comment] 2019-12-21 01:26
I apologize for not specifying in the original post. This is on an IPad, 6th generation, with IPadOS 13.2.3.

**Comment by Zosoled** [comment] 2019-12-25 02:39
Should be closed as duplicate of #103

**Comment by brandosha** [comment] 2020-01-07 23:33
Probably the same as this issue: https://github.com/brandosha/gameplaycolor/issues/4

**Comment by jbmorley** [comment] 2021-05-15 22:54
Closing as duplicate.

**Comment by jbmorley** [comment] 2021-05-25 22:48
I think I incorrectly closed this as a duplicate of #103. As it is, I think it's probably the problem where iPadOS reports itself as a Mac to convince sites to give it the desktop page.

**Comment by jbmorley** [comment] 2021-05-25 23:10
I've updated the title to try to make it clearer what's going on with this issue.

**Comment by jbmorley** [comment] 2021-05-28 16:51
Fixed in #185.

**Closed by jbmorley** 2021-05-28 16:51 UTC
Labels: bug
