### ISSUE TITLE
The app doesn’t work

### ISSUE THREAD

**Issue by Davidomar123** [gameplaycolor/gameplaycolor#124] opened 2019-12-20 19:13 UTC
I saved the app on the home screen and when I opened it I found the same instructions on the page to put the app on the home screen and I didn't let myself register or play, help me.

**Comment by imethorsen** [comment] 2019-12-21 00:15
Perhaps a duplicate of https://github.com/gameplaycolor/gameplaycolor/issues/123?

**Comment by Davidomar123** [comment] 2019-12-21 00:18
What?

**Comment by imethorsen** [comment] 2019-12-21 00:19
What device are you using this on?

**Comment by Davidomar123** [comment] 2019-12-21 02:24
iPadOS iOS 13

**Comment by jbmorley** [comment] 2019-12-21 10:23
Thank you for clarifying. It looks like this is the same as the issue that is being tracked here as issue https://github.com/gameplaycolor/gameplaycolor/issues/123. Game Play does not work with iPadOS 13.

**Comment by Zosoled** [comment] 2019-12-25 02:39
Should be closed as duplicate of #103

**Comment by brandosha** [comment] 2020-01-07 23:28
Probably the same as this issue: https://github.com/brandosha/gameplaycolor/issues/4

**Comment by jbmorley** [comment] 2021-05-25 23:09
Thanks everyone for chiming in with your suggestions here. I'm pretty sure @brandosha is right: this is the issue where iPadOS pretends to be a Mac. I'm pretty sure that's fixed on his fork, but I've not had a chance to look at it yet (maybe one of these days we can collect all this wonderful work up in one place). Until then, I'm going to close this as a duplicate of issue #123 which is tracking the iPad issues.

I know this has been sitting open for a while now; I'll try to look into it soon.

**Closed by jbmorley** 2021-05-25 23:09 UTC
Labels: bug
