### ISSUE TITLE
Rom save issue

### ISSUE THREAD

**Issue by MagicM007** [gameplaycolor/gameplaycolor#134] opened 2020-03-15 10:07 UTC
I played two different ROMs for Dragon Quest monsters, but everything (far in the game) when I win the star tournament, the ROM saves and ask me to shut the Gameboy and restart it again afterwards. Everytime I restart, the game starts the mast save file before winning the tournament, which is why I cannot proceed. Is there any way to check why the emulator has this issue?

**Comment by jbmorley** [comment] 2021-05-25 22:58
@MagicM007 Thanks for raising the issue. 🙏🏻

Unfortunately this problem manifests for any games that require a power-cycle to 'finish' the game. Right now, I don't know exactly why that is, and what exactly the difference is but there must be _something_ different.

I'm going to close this as a duplicate of #81 as I think that's probably going to be the correct way to address this. Do please feel free to follow along there. I've personally never completed a game which requires this, so I might well ask you to contribute your save game to the debugging process nearer the time if that's something you're willing to share.

**Closed by jbmorley** 2021-05-25 22:58 UTC
