### ISSUE TITLE
BUSTED IOS13

### ISSUE THREAD

**Issue by no0bi1** [gameplaycolor/gameplaycolor#107] opened 2019-10-11 15:51 UTC
What’s going on?

**Comment by 10acity420** [comment] 2019-10-14 19:24
I have no clue, I think that the protocol they use for ios has been replaced creating a whole myriad of issues with the new ios update.

**Comment by nickydraz** [comment] 2019-10-19 01:11
This is likely the same issue as #103 . I have created a PR #108 that should fix the issue.

**Comment by Zosoled** [comment] 2019-12-25 02:38
Should be closed as duplicate of #103

**Comment by jbmorley** [comment] 2021-05-25 21:51
Closing as duplicate.

**Closed by jbmorley** 2021-05-25 21:51 UTC
Labels: duplicate
