### ISSUE TITLE
Error- doesn’t work

### ISSUE THREAD

**Issue by Fynzerious** [gameplaycolor/gameplaycolor#147] opened 2020-12-14 19:42 UTC
![58A7EC18-439E-4DC9-B388-995E40F4B9B6](https://user-images.githubusercontent.com/76009696/102126698-55507800-3e43-11eb-9441-e3826435255b.png)
This is the screen where it tells you to add it to your home page
![B060410C-4C51-4FB8-81AA-371CA9E57988](https://user-images.githubusercontent.com/76009696/102127244-2d154900-3e44-11eb-8b50-1336b15e6122.jpeg)
It’s also the screen that shows up when I click the app that I added to my home screen(the Game Play app)
It works just fine on my iPhone but for some reason not on my iPad.
I don’t know how to fix this and I need help. Please.

**Comment by jbmorley** [comment] 2020-12-15 01:17
I believe this is due to changes in iOS 14 which cause the iPad browser to masquerade as a Mac to ensure websites serve up the full experience (and not iPhone optimised versions of the sites). Unfortunately in the case of Game Play, it means that the logic used to determine when to show instructions is now outdated and wrong. It shouldn't be a big change to adjust the logic; I'll try to take a look soon if I get the time.

**Comment by Fynzerious** [comment] 2020-12-15 14:02
Thank you so much!
If there ever is a change comment here please. I’ll be looking at it every couple days.

**Comment by Ihaveacat3321** [comment] 2020-12-18 21:05
Just figured out a way to solve this. Before you add the shortcut to your Home Screen, click on the AA to the left of the URL, next to the bookmark icon. Then, go to “website settings” and disable “request desktop site”

**Comment by jbmorley** [comment] 2021-05-26 00:16
Closing as a duplicate of #123.

**Closed by jbmorley** 2021-05-26 00:16 UTC
