### ISSUE TITLE
Add support for playing game boy advance games

### ISSUE THREAD

**Issue by brismuth** [gameplaycolor/gameplaycolor#121] opened 2019-12-17 23:00 UTC
This is a fantastic example of what can be done with a PWA - great work!

I was wondering if you've considered extending this emulator to support gameboy advance games as well. It looks like Grant Galitz has now built a GBA emulator core for JS as well: https://github.com/taisel/IodineGBA

Thoughts?

**Comment by jbmorley** [comment] 2021-05-26 00:44
@brismuth It's a great idea 🎉. I would _LOVE_ to add additional console support. Unfortunately I've not been able to look at Game Play Color for a while due to some professional restrictions, but I'm slowly paging this all back in and, ... just maybe I'll see if we can do something here. All that said, I'm going to close this issue as a dupe of #155 where I'm going to try to track requests.

**Closed by jbmorley** 2021-05-26 00:44 UTC
Labels: enhancement
