### ISSUE TITLE
Unable to launch app in Safari 13

### ISSUE THREAD

**Issue by DanielJMonroe** [gameplaycolor/gameplaycolor#103] opened 2019-07-01 19:17 UTC
I recently installed the public beta for iOS 13 and I have noticed an issue with Game Play Color. Here is the flow of events. 

1. Visiting gameplaycolor.com, I am prompted with a message, "Databases are not supported in this browser".
2. Dismissing this message prompts another message, "Unable to create database. Please accept increased storage size when asked."
3. Dismissing this message takes me to gameplaycolor.com/app with no prompt about storage size.
4. I follow the instructions to create the shortcut on the home screen.
5. Launching the shortcut takes me to a blank white screen for about 10 seconds, before taking me through the messages in Steps 1 and 2.
6. Screen turns black and stays that way indefinitely.

I did some digging and the message about storage size seems to be related to WebSQL, which is being deprecated for Safari 13. Safari 13 has a setting for "Disable WebSQL" which is selected by default. I tried disabling this switch and following the steps again. The results were the same, although I did not receive the messages in Steps 1 and 2. The messages did however appear during Step 5.

**Comment by jeffreylanters** [comment] 2019-07-22 07:38
I’m running into the same problems on Developer beta 4. However, you can turn WebSQL back on via the Settings app > Safari > Advanced > Expirmental Features. But this is still a temporary fix, Apple will eventually remove it from iOS all together.

**Comment by player13377** [comment] 2019-08-05 17:03
Hi, have you found any solution to the problem?

**Comment by ewancube** [comment] 2019-09-06 12:25
I can confirm this issue as reported. Also propagates to Chrome on iOS, presumably due to WebKit. Please escalate as this is a blocking issue on the platform.

**Comment by Archangelx72** [comment] 2019-09-21 03:16
Is this issue going to be fixed? I’m desperate to keep playing my games?

**Comment by czpta** [comment] 2019-09-25 13:03
I’m not sure any of us can demand for the creator to make an update to IndexedDB (this is what Apple wants to use moving forward). I haven’t taken a look at how pull requests are managed on this repo but one proposal is reaching out to emulator boards (reddit?) and hoping someone familiar with the technology also loves IndexedDB

**Comment by jeffreylanters** [comment] 2019-09-26 10:34
@czpta there does not seem to be a continuous integration or automated deployment on this repo. So even if we upgrade to Indexed Databases, someone should either get the maintainer to publish it or any of us should re-host the whole thing.

**Comment by nickydraz** [comment] 2019-10-06 04:40
I've got a fork of GPC going that has been updated to use IndexedDB. It seems to be 99% there, but for some reason when I try to run a ROM, it shows the console frame, but the screen stays white instead of running the ROM. I'm not sure if this was happening with the code I forked from since I couldn't run it on my phone after updating to iOS 13.

If anyone is able to get me past that issue, I'd love it. I've also never done anything with IndexedDB or WebSQL before this, so if any of the code around that migration needs to be cleaned up and people have the knowhow to do that cleanup, I'd appreciate the help in that area as well. 

Fork is at https://github.com/nickydraz/gameplaycolor if anyone is interested.

**Comment by nickydraz** [comment] 2019-10-06 14:47
Was actually able to figure it out. Had a bug in my implementation of propertiesForDomain with the new IndexedDB logic. Created a PR to get the refactored db code brought in. Hopefully it gets merged in sometime soon so we can play our games again.

**Comment by brandosha** [comment] 2019-10-18 20:39
I created a fork of @nickydraz’s fork that works from my testing and I am hosting it [here](https://brandosha.github.io/gameplay/index.html)

**Comment by nickydraz** [comment] 2019-10-19 01:11
Closed my original PR because of a caching issue I had when hosting on my own server. Found it was just because it was checking for updates at gameplaycolor.com and not my custom domain. 

Glad I waited too, since @brandosha found and fixed an annoying issue.

Created PR #108 . Hopefully it gets accepted soon.

**Comment by 47yellow** [comment] 2019-10-20 17:30
Hi @brandosha thank you for hosting. 

Does anyone know if it is possible to get the saved states from the old version? Sad as I am I’m nearly through completing Zelda 😂

**Comment by brandosha** [comment] 2019-10-20 17:35
@47yellow I don’t think that it is even possible to access the old data, it is possible that once you updated all of the Web SQL data was deleted, I will look into it though

**Comment by brandosha** [comment] 2019-10-21 15:07
@47yellow because gameplay is a PWA turning WebSQL back on doesn’t affect it and I can’t access the data from the Safari developer tools so the only way I can think of would be to downgrade back to iOS 12, get the save data from the `saveState` variable, upgrade again, and import the data again. Seems like too much of a hassle for Zelda though 😂

**Comment by brandosha** [comment] 2019-10-21 15:53
Also for anyone interested my fork is located here: [brandosha/gameplaycolor](https://github.com/brandosha/gameplaycolor)

**Comment by cry0sync** [comment] 2019-11-01 03:45
> Also for anyone interested my fork is located here: [brandosha/gameplaycolor](https://github.com/brandosha/gameplaycolor)

Hey @brandosha maybe a dumb question, but I've noticed that you added the ability to save game states to Google Drive.  Where are these files saved on Drive?  Thanks for your work!

**Comment by brandosha** [comment] 2019-11-01 14:50
@cry0sync it is saved in a hidden app data folder, so it currently isn't possible to import/export game state to/from a different emulator, I am hoping to add that functionality at some point though. It is meant for if you have multiple devices and want to sync your save data

**Comment by cry0sync** [comment] 2019-11-04 00:23
> @cry0sync it is saved in a hidden app data folder, so it currently isn't possible to import/export game state to/from a different emulator, I am hoping to add that functionality at some point though. It is meant for if you have multiple devices and want to sync your save data

Awesome, sounds good.  Thanks for the info! :)

**Comment by firegreninja155** [comment] 2019-11-24 18:23
This might sound a bit stupid but how do I actually download the app?

**Comment by ewancube** [comment] 2019-11-24 18:40
> This might sound a bit stupid but how do I actually download the app?

A couple things...

Your question is unrelated to this issue so this is the wrong place for it. Don’t intend for that to come off as mean - just letting you know this isn’t the right place for that kinda help.

Second, this emulator is not an “app” in the traditional iOS sense. It is essentially a web application. Now you can put a shortcut for it on your iOS device by opening the webpage in Safari, accessing the sharing panel, and choosing “Add to Home Screen”. Hope that helps!

**Comment by SaltyKoala** [comment] 2019-11-24 20:15
So am i dumb and missed it, or is there no fix as of now for this other then going back to a older iOS version?

**Comment by nickydraz** [comment] 2019-11-24 20:17
@brandosha hosts a fixed version here: https://brandosha.github.io/gameplay/index.html

I have a pull request with the fix in it, just hasn’t been approved/merged in yet. So it is going to remain an issue on the official web app until that happens.

**Comment by ewancube** [comment] 2019-11-24 20:18
Yeah, I’ve been using the @brandosha hosted fork without any issues so far.

**Comment by SaltyKoala** [comment] 2019-11-24 20:35
@nickydraz Yep that worked! Thank for the help!

**Comment by firegreninja155** [comment] 2019-11-25 20:31
Here is an issue I have run into:
When I click the link and add to my home screen I clicked on the shortcut but it repeated with the same message:
1. Open in Mobile Safari on your iPhone or iPad
2. Tap the ‘Share’ button
3. Choose ‘Add to Home Screen’
Is there something I’m missing or?

**Comment by brandosha** [comment] 2019-11-25 20:40
@firegreninja155 this could be caused if you have your default webpage settings to use desktop website, when you open the page in Safari open the site preferences and make sure it defaults to the mobile site

**Comment by firegreninja155** [comment] 2019-11-25 20:44
Ok I’ll try that, thank you.

**Comment by firegreninja155** [comment] 2019-11-25 20:53
Oh my gosh it worked, Thank you very much :D

**Comment by grundleface** [comment] 2019-12-02 01:31
So I've tried using Brandosha's fork(?) and I'm getting stuck. I'll get to the point of allowing game play to use my Drive, but get sent to a "Page Not Found" on the Game Play site and don't have an access code.

**Comment by imethorsen** [comment] 2019-12-02 05:26
We're working on updating the gameplaycolor.com hosted version. Hopefully that will be ready for use soon; I will update this issue when it is.

**Comment by hero2779** [comment] 2019-12-03 15:52
Having the same issue as grundleface 
Please let me know if this gets fixed

**Comment by brandosha** [comment] 2019-12-04 15:08
@grundleface @hero2779 I just updated my hosted version, but hopefully gameplaycolor.com will be fixed soon

**Comment by ewancube** [comment] 2019-12-04 16:01
> @grundleface @hero2779 I just updated my hosted version, but hopefully gameplaycolor.com will be fixed soon

Just upgraded to 3.0.4 on your hosted and it’s looking solid so far. 👍🏻

**Comment by ewancube** [comment] 2019-12-04 16:18
> > @grundleface @hero2779 I just updated my hosted version, but hopefully gameplaycolor.com will be fixed soon
> 
> Just upgraded to 3.0.4 on your hosted and it’s looking solid so far. 👍🏻

Actually there may be an issue with save files. Got the notice of new version. Restarted app. Logged out of Google Drive and then in again. Playing SMB Deluxe and saved (not state - normal game save). Closed app. Reopen app, start SMB Deluxe and it has reverted to previous save (prior to 3.0.4). I’m not filing an issue as this is not the officially hosted version but wanted to let you know.

**Comment by brandosha** [comment] 2019-12-04 17:34
File an issue [here](https://github.com/brandosha/gameplaycolor) and I will look into it ASAP

**Comment by ewancube** [comment] 2019-12-04 20:14
> File an issue [here](https://github.com/brandosha/gameplaycolor) and I will look into it ASAP

It doesn’t appear that you’ve enabled issues in your fork’s settings. Or at least that appears to be the case as I don’t have the option to create an issue.

**Comment by brandosha** [comment] 2019-12-05 01:54
@ewancube I created an [issue](https://github.com/brandosha/gameplaycolor/issues/1). Also I haven't been able to reproduce the problem so any help would be appreciated.

**Comment by hero2779** [comment] 2019-12-05 03:34
Brandosha I can tell you now everyone in my school is going to love you. Half of us use game play in our boring classes like Spanish and crap and now that you’ve fixed it for us we are back to it

**Comment by Zosoled** [comment] 2019-12-05 18:33
@brandosha 's version 3.0.5 is working great for me on iOS 13.2.3
https://brandosha.github.io/gameplay/index.html

**Comment by Zosoled** [comment] 2019-12-25 16:48
@brandosha 's version 3.1.2 is still working for me on iOS 13.3
https://brandosha.github.io/gameplay/index.html

**Comment by jbmorley** [comment] 2021-05-25 21:51
Closing as fixed thanks to the PR by @nickydraz. 🎉🎉🙏🏻

**Closed by jbmorley** 2021-05-25 21:51 UTC
