### ISSUE TITLE
This app is blocked. Google issue.

### ISSUE THREAD

**Issue by AdriSoup** [gameplaycolor/gameplaycolor#241] opened 2024-08-06 22:35 UTC
This app is blocked. This app tried to access sensitive info in your Google Account. To keep your account safe, Google blocked this access.
![imagen_2024-08-07_003451222](https://github.com/user-attachments/assets/3ab618d7-c677-4fef-bf29-21b726215670)
How can i fix this :( yesterday gameplaycolor worked fine but now i cant play.

**Comment by HellDan91** [comment] 2024-08-29 16:45
Same problem here. Google changed some things in their policy. Its no longer possible to connect third party apps wich are not verified by google. Please Gameplay Color Team react! I need my gameboy back.

**Comment by jbmorley** [comment] 2024-08-29 17:21
Yeah. This all sucks, I agree. Google's been getting more and more painful here and it's not something I'm not willing to keep up with any more—I've already verified the app multiple times but they keep changing the goal posts. With all the kinds of changes lately, I don't really trust the platform to hang around.

So! I'm currently working on a rework of Game Play which drops support for Google Drive entirely and lets you add games from your local device. It also drops the iOS restriction so Android users should be able to have fun. My plan, right now, is to ensure that games you've already added from your Google Drive (downloaded and played), will remain in your local archive and save states will be preserved.

The theory is that these changes will generally make Game Play more reliable and ensure it keeps working into the future irrespective of what Google or others decide to do.

**Comment by jbmorley** [comment] 2024-08-29 17:23
I'm going to close this issue as a duplicate of #240. Be assured I'm tracking it, and feel free to continue any discussion on that issue.

**Closed by jbmorley** 2024-08-29 17:23 UTC
