### ISSUE TITLE
All I want is to transfer my save data

### ISSUE THREAD

**Issue by supernoobwt** [gameplaycolor/gameplaycolor#82] opened 2017-05-23 18:17 UTC
I have been trying to copy the repository to my desktop for GitHub but it does not seem to be working. As you can tell by my name, I am a noob at this. All I have been trying to do is find my save data from gameplay so that I can put transfer it to Dropbox with GBA4ios

**Comment by jbmorley** [comment] 2021-05-16 14:30
Closing as a duplicate of #46.

**Closed by jbmorley** 2021-05-16 14:30 UTC
