### ISSUE TITLE
Would like to reposition the buttons

### ISSUE THREAD

**Issue by MertDalbudak** [gameplaycolor/gameplaycolor#104] opened 2019-08-12 08:14 UTC
My thumb hurts while playing because the buttons are at the very bottom of the screen
so it is harder to play on my iPhone Xr when playing more than 2 hours. Even I have not that big hands.

Is there any way to "Drag and drop" Buttons to reposition them? If this will be available it would be a nice feature!

**Comment by jbmorley** [comment] 2021-05-25 22:13
@MertDalbudak Thanks for the suggestion. I think this is a duplicate of #70 so I'm going to close it and track the request there. Please feel free to join any discussion. 🙏🏻

**Closed by jbmorley** 2021-05-25 22:13 UTC
