### ISSUE TITLE
Emulation speed is not maintained after game restarts

### ISSUE THREAD

**Issue by keydee** [gameplaycolor/gameplaycolor#92] opened 2018-03-06 09:52 UTC
I'm on iOS 11.2.6 on iPhone 6.

I setup my SETTINGS to be on 3.0 emulation speed. First play is fine, it's fast, but after I close the game and open it again, the game slows down to normal, even though the gameboy's SETTINGS are still on 3.0 speed.

Changing it back from 3.0 to 1.0 speed and to 3.0 again, doesn't help.
Only thing that helps is reinstalling the emulator and thus starting the game all over.

**Comment by ajbrensike** [comment] 2019-08-17 04:59
I am having this same issue even now, did you ever figure out a fix? Sadly I forgot about the game saving locally so when I deleted the emulator and reinstalling it I lost my save. After going for about 3 days somehow with no issues it has happened again. I can play it on the "normal 3.0" speed but would really prefer a fix to be able to revert it back to the actual fast 3.0 speed.

**Comment by Xman3684** [comment] 2021-03-30 00:35
in order for this to maintain, make sure you "enable sound" on start up

**Comment by bigpeenjanine** [comment] 2023-09-02 21:05
> I'm on iOS 11.2.6 on iPhone 6.
> 
> I setup my SETTINGS to be on 3.0 emulation speed. First play is fine, it's fast, but after I close the game and open it again, the game slows down to normal, even though the gameboy's SETTINGS are still on 3.0 speed.
> 
> Changing it back from 3.0 to 1.0 speed and to 3.0 again, doesn't help. Only thing that helps is reinstalling the emulator and thus starting the game all over.

This issue is caused by low power mode. Disabling low power mode in iOS should fix the speeds

**Comment by jbmorley** [comment] 2024-08-29 21:48
So this dates back to 2019 and I can't seem to reproduce it, try as I might. Closing it as invalid. We can re-open or create a new issue if we see it again.

**Closed** 2024-08-29 21:48 UTC
Labels: bug, invalid
