### ISSUE TITLE
Req: Gameshark cheat codes

### ISSUE THREAD

**Issue by NimbleSlimble** [gameplaycolor/gameplaycolor#235] opened 2023-09-30 15:18 UTC
firstly thank you for what I believe to be the superior gbc emulator. Just wanted to request gameshark cheat codes would be absolutely perfect with that addition. 

Thanks

**Comment by jbmorley** [comment] 2023-10-03 21:32
@NimbleSlimble Thanks for the great feedback! There's already an issue open tracking support for cheat codes (#51) so I'm going to close this one and you can follow along on there. Unfortunately, I've not had much chance to work on Game Play over the last few years so it might take a while, but hopefully I'll get to it one of these days. 🤞🏻

**Comment by jbmorley** [comment] 2023-10-03 21:32
Duplicate of #51.

**Closed by jbmorley** 2023-10-03 21:32 UTC
